### ISSUE TITLE
Issue swiping left when on last slide

### ISSUE THREAD

**Issue by jackbrewer** [loryjs/lory#670]
Hi, I've encountered a bug when trying to use fixed-width slides in a non-infinite slider.

If you swipe/drag to the last slide, it is impossible to get back to the last-1 slide. This is causing me issues as I I'd like to be able to have a slider with 2 slides. The result is the User gets stuck on the second slide, as they cannot swipe back to the first.

Adding `rewind: true` kinda works as a workaround, but is not intuitive as you nee to "swipe right to go left", whilst actually swiping left does nothing.

Reduced test case:
https://codepen.io/jackbrewer/pen/qmKXXZ

Any help greatly appreciated :)

**Comment by nstanard** [comment]
@jackbrewer Thank you for providing a link to a reduced test case. I greatly appreciate that and I will take a look at this in the evening today. I will get back to you with what I find.

**Comment by tournevis** [comment]
Hi, 

I'm having the same issue with non-infinite slider

@jackbrewer The last slide, never get the 'active' class, so that's why in the first case you can't get back on first slide cause lory still thinks that the first slide is active. 

 @nstanard  did you find any clue that will orientate us ?  😀

**Comment by luksladky** [comment]
It causes the condition for updating index in the slide() method. The offsetLeft is slightly higher that the maxOffset (by 3px in my case). I don't know why is this happening though.

`                    if (slides[nextIndex].offsetLeft <= maxOffset) {
                        index = nextIndex;
                    }`

**Comment by maxkliu26** [comment]
I encountered the same error and it seems that the issue is caused by the following codes (where the maxOffset is smaller than the offsetLeft, resulting the class 'active' isn't updated)

if (slides[nextIndex].offsetLeft <= maxOffset) {
  index = nextIndex;
}

Currently my workaround is to "change" the width of the frame based on the calculated breakpoints and the width of my card in my css file. That's

.slider .frame {
   width: 315px; /* this is the width of my card. */
}

/* 662px is calculated based on the width of my cards and associated margins */
@media only screen and (min-width: 662px) {
    .slider .frame {
        width: 630px; 
    }
}

...

So far, i got only a drawback where the spacing might be a bit "off" when users swipe the card in some viewports but at least the user experience would be better, since users could swipe back now. Hopefully it helps and if there is any better approach or solution, feel free to suggest here. :)
